<a href="https://colab.research.google.com/github/supermanimmy/ca-machine-learning-with-scikit-learn/blob/main/PyTorch101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_data = [[1,2], [3,4]]

In [ ]:
torch.tensor(my_data)

tensor([[1, 2],
        [3, 4]])

In [ ]:
my_tensor = torch.tensor(my_data)

my_tensor.dtype

torch.int64

In [ ]:
my_tensor.type()

'torch.LongTensor'

In [ ]:
type(my_tensor)

torch.Tensor

In [ ]:
my_tensor.device

device(type='cpu')

In [ ]:
my_tensor.to('cuda')

tensor([[1, 2],
        [3, 4]], device='cuda:0')

In [ ]:
torch.cuda.current_device()

0

In [ ]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
new_tensor = torch.ones(2,2)

In [ ]:
new_tensor.dtype

torch.float32

In [ ]:
new_tensor.type()

'torch.FloatTensor'

In [ ]:
update_tensor = new_tensor.new_tensor(my_data)

In [ ]:
update_tensor.dtype

torch.float32

In [ ]:
another_tensor = torch.ones((2,2), dtype=torch.int8, device='cuda')

In [ ]:
another_tensor

tensor([[1, 1],
        [1, 1]], device='cuda:0', dtype=torch.int8)

In [ ]:
another_tensor.new_tensor(my_data)

tensor([[1, 2],
        [3, 4]], device='cuda:0', dtype=torch.int8)

In [ ]:
another_tensor.device

device(type='cuda', index=0)

In [ ]:
new_data = [[1,2], [3,4], [5,6]]
another_tensor.new_tensor(new_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0', dtype=torch.int8)

In [ ]:
shape = (2,3)

my_tensor = torch.rand(shape)

In [ ]:
my_tensor

tensor([[0.7005, 0.7507, 0.4124],
        [0.0709, 0.1279, 0.0704]])

In [ ]:
torch.rand_like(my_tensor, dtype=torch.float)

tensor([[0.8931, 0.5199, 0.7208],
        [0.6079, 0.4821, 0.6882]])