<a href="https://colab.research.google.com/github/supermanimmy/ca-machine-learning-with-scikit-learn/blob/main/Tensor_in_PyTorch_Part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensors in PyTorch- Part 2**

In [2]:
import numpy as np
numpy_data = np.random.rand(2,3)

In [3]:
numpy_data

array([[0.54548472, 0.76391999, 0.2176934 ],
       [0.66409915, 0.36194424, 0.8628109 ]])

In [4]:
import torch
torch_numpy = torch.from_numpy(numpy_data)

In [5]:
torch_numpy

tensor([[0.5455, 0.7639, 0.2177],
        [0.6641, 0.3619, 0.8628]], dtype=torch.float64)

In [6]:
tensor_numpy_direct = torch.tensor(numpy_data)

In [7]:
tensor_numpy_direct

tensor([[0.5455, 0.7639, 0.2177],
        [0.6641, 0.3619, 0.8628]], dtype=torch.float64)

Moving tenser that's on GPU to simple numpy array, you will get a numpy array that is entirely on CPU, without the need for GPU

In [8]:
tensor_numpy_direct.cpu().numpy()

array([[0.54548472, 0.76391999, 0.2176934 ],
       [0.66409915, 0.36194424, 0.8628109 ]])

## Operations between tensors
Being able to perform operations between tensors is important.
We will first investigate concatenating two or more tensors

In [9]:
numpy_data = np.random.rand(2,3)

In [10]:
numpy_data

array([[0.3424276 , 0.14418737, 0.23896021],
       [0.49348956, 0.16221229, 0.67623277]])

In [11]:
my_tns2 = torch.tensor(numpy_data)

In [12]:
my_tns1 = torch_numpy

In [13]:
my_tns1

tensor([[0.5455, 0.7639, 0.2177],
        [0.6641, 0.3619, 0.8628]], dtype=torch.float64)

### To concatenate, we use the cat method

In [14]:
torch.cat([my_tns1, my_tns2], dim=1) # set dim=1 to concate on columns, 0 for rows.

tensor([[0.5455, 0.7639, 0.2177, 0.3424, 0.1442, 0.2390],
        [0.6641, 0.3619, 0.8628, 0.4935, 0.1622, 0.6762]], dtype=torch.float64)

### Another operation is to clip, apply an upper and lower bound to generated data

In [15]:
my_tns2.clip(0.3, 0.7)

tensor([[0.3424, 0.3000, 0.3000],
        [0.4935, 0.3000, 0.6762]], dtype=torch.float64)

### Element-wise multiplication
Element-wise multiplication of two matrices is also called Hadamard product, and is done with the method mul.

In [16]:
my_tns1.mul(my_tns2) # rounds to 4 decimal places.

tensor([[0.1868, 0.1101, 0.0520],
        [0.3277, 0.0587, 0.5835]], dtype=torch.float64)

In [17]:
my_tns1 * my_tns2 # same as the mul() method above

tensor([[0.1868, 0.1101, 0.0520],
        [0.3277, 0.0587, 0.5835]], dtype=torch.float64)

In [19]:
my_tns1.matmul(my_tns2.T) #doesn't work without Transpose here, 2x3 cannot be multiplied by 2x3 so we change it to 3x2

tensor([[0.3490, 0.5403],
        [0.4858, 0.9699]], dtype=torch.float64)

In [22]:
my_tns1 @ my_tns2.T #same as using matmul() above

tensor([[0.3490, 0.5403],
        [0.4858, 0.9699]], dtype=torch.float64)

#### Scalar Tensor

In [24]:
my_sum  = my_tns2.sum()

In [25]:
my_sum

tensor(2.0575, dtype=torch.float64)

In [26]:
my_sum.item()

2.057509803831413

In [28]:
type(my_sum), type(my_sum.item()) #if you don't want to work with tensors, use the item to turn it into python float

(torch.Tensor, float)

In [38]:
matrix_A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [39]:
matrix_A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [40]:
matrix_B = matrix_A.clone()

In [41]:
matrix_A + matrix_B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [42]:
matrix_B.type() # in pytorch you can't calculate the mean of integer types, we will go back and make matrix A dtype float in initialisation

'torch.FloatTensor'

In [46]:
matrix_B.mean(dim=0), matrix_B.mean(dim=1)

(tensor([ 8.,  9., 10., 11.]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]))

In [48]:
matrix_B.sum(axis=0)/matrix_B.shape[0] # can obtain the same result as .mean() by using the sum and shape method

tensor([ 8.,  9., 10., 11.])